// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ChangeStatusRequestStatus.
const (
	ChangeStatusRequestStatusDELISTED   ChangeStatusRequestStatus = "DELISTED"
	ChangeStatusRequestStatusOCCUPIED   ChangeStatusRequestStatus = "OCCUPIED"
	ChangeStatusRequestStatusRENOVATING ChangeStatusRequestStatus = "RENOVATING"
	ChangeStatusRequestStatusVACANT     ChangeStatusRequestStatus = "VACANT"
)

// Valid indicates whether the value is a known member of the ChangeStatusRequestStatus enum.
func (e ChangeStatusRequestStatus) Valid() bool {
	switch e {
	case ChangeStatusRequestStatusDELISTED:
		return true
	case ChangeStatusRequestStatusOCCUPIED:
		return true
	case ChangeStatusRequestStatusRENOVATING:
		return true
	case ChangeStatusRequestStatusVACANT:
		return true
	default:
		return false
	}
}

// Defines values for CreatePropertyRequestLayout.
const (
	CreatePropertyRequestLayoutINDEPENDENTSUITE CreatePropertyRequestLayout = "INDEPENDENT_SUITE"
	CreatePropertyRequestLayoutSHAREDSUITE      CreatePropertyRequestLayout = "SHARED_SUITE"
	CreatePropertyRequestLayoutSINGLEROOM       CreatePropertyRequestLayout = "SINGLE_ROOM"
	CreatePropertyRequestLayoutWHOLEUNIT        CreatePropertyRequestLayout = "WHOLE_UNIT"
)

// Valid indicates whether the value is a known member of the CreatePropertyRequestLayout enum.
func (e CreatePropertyRequestLayout) Valid() bool {
	switch e {
	case CreatePropertyRequestLayoutINDEPENDENTSUITE:
		return true
	case CreatePropertyRequestLayoutSHAREDSUITE:
		return true
	case CreatePropertyRequestLayoutSINGLEROOM:
		return true
	case CreatePropertyRequestLayoutWHOLEUNIT:
		return true
	default:
		return false
	}
}

// Defines values for CreatePropertyRequestRentalMode.
const (
	CreatePropertyRequestRentalModeMANAGED     CreatePropertyRequestRentalMode = "MANAGED"
	CreatePropertyRequestRentalModeMASTERLEASE CreatePropertyRequestRentalMode = "MASTER_LEASE"
)

// Valid indicates whether the value is a known member of the CreatePropertyRequestRentalMode enum.
func (e CreatePropertyRequestRentalMode) Valid() bool {
	switch e {
	case CreatePropertyRequestRentalModeMANAGED:
		return true
	case CreatePropertyRequestRentalModeMASTERLEASE:
		return true
	default:
		return false
	}
}

// Defines values for HealthReportStatus.
const (
	Degraded HealthReportStatus = "degraded"
	Ok       HealthReportStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthReportStatus enum.
func (e HealthReportStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for PropertyLayout.
const (
	PropertyLayoutINDEPENDENTSUITE PropertyLayout = "INDEPENDENT_SUITE"
	PropertyLayoutSHAREDSUITE      PropertyLayout = "SHARED_SUITE"
	PropertyLayoutSINGLEROOM       PropertyLayout = "SINGLE_ROOM"
	PropertyLayoutWHOLEUNIT        PropertyLayout = "WHOLE_UNIT"
)

// Valid indicates whether the value is a known member of the PropertyLayout enum.
func (e PropertyLayout) Valid() bool {
	switch e {
	case PropertyLayoutINDEPENDENTSUITE:
		return true
	case PropertyLayoutSHAREDSUITE:
		return true
	case PropertyLayoutSINGLEROOM:
		return true
	case PropertyLayoutWHOLEUNIT:
		return true
	default:
		return false
	}
}

// Defines values for PropertyRentalMode.
const (
	PropertyRentalModeMANAGED     PropertyRentalMode = "MANAGED"
	PropertyRentalModeMASTERLEASE PropertyRentalMode = "MASTER_LEASE"
)

// Valid indicates whether the value is a known member of the PropertyRentalMode enum.
func (e PropertyRentalMode) Valid() bool {
	switch e {
	case PropertyRentalModeMANAGED:
		return true
	case PropertyRentalModeMASTERLEASE:
		return true
	default:
		return false
	}
}

// Defines values for PropertyStatus.
const (
	PropertyStatusDELISTED   PropertyStatus = "DELISTED"
	PropertyStatusOCCUPIED   PropertyStatus = "OCCUPIED"
	PropertyStatusRENOVATING PropertyStatus = "RENOVATING"
	PropertyStatusVACANT     PropertyStatus = "VACANT"
)

// Valid indicates whether the value is a known member of the PropertyStatus enum.
func (e PropertyStatus) Valid() bool {
	switch e {
	case PropertyStatusDELISTED:
		return true
	case PropertyStatusOCCUPIED:
		return true
	case PropertyStatusRENOVATING:
		return true
	case PropertyStatusVACANT:
		return true
	default:
		return false
	}
}

// Defines values for UpdatePropertyRequestLayout.
const (
	UpdatePropertyRequestLayoutINDEPENDENTSUITE UpdatePropertyRequestLayout = "INDEPENDENT_SUITE"
	UpdatePropertyRequestLayoutSHAREDSUITE      UpdatePropertyRequestLayout = "SHARED_SUITE"
	UpdatePropertyRequestLayoutSINGLEROOM       UpdatePropertyRequestLayout = "SINGLE_ROOM"
	UpdatePropertyRequestLayoutWHOLEUNIT        UpdatePropertyRequestLayout = "WHOLE_UNIT"
)

// Valid indicates whether the value is a known member of the UpdatePropertyRequestLayout enum.
func (e UpdatePropertyRequestLayout) Valid() bool {
	switch e {
	case UpdatePropertyRequestLayoutINDEPENDENTSUITE:
		return true
	case UpdatePropertyRequestLayoutSHAREDSUITE:
		return true
	case UpdatePropertyRequestLayoutSINGLEROOM:
		return true
	case UpdatePropertyRequestLayoutWHOLEUNIT:
		return true
	default:
		return false
	}
}

// Defines values for ListPropertiesParamsStatus.
const (
	ListPropertiesParamsStatusDELISTED   ListPropertiesParamsStatus = "DELISTED"
	ListPropertiesParamsStatusOCCUPIED   ListPropertiesParamsStatus = "OCCUPIED"
	ListPropertiesParamsStatusRENOVATING ListPropertiesParamsStatus = "RENOVATING"
	ListPropertiesParamsStatusVACANT     ListPropertiesParamsStatus = "VACANT"
)

// Valid indicates whether the value is a known member of the ListPropertiesParamsStatus enum.
func (e ListPropertiesParamsStatus) Valid() bool {
	switch e {
	case ListPropertiesParamsStatusDELISTED:
		return true
	case ListPropertiesParamsStatusOCCUPIED:
		return true
	case ListPropertiesParamsStatusRENOVATING:
		return true
	case ListPropertiesParamsStatusVACANT:
		return true
	default:
		return false
	}
}

// Defines values for ListPropertiesParamsRentalMode.
const (
	ListPropertiesParamsRentalModeMANAGED     ListPropertiesParamsRentalMode = "MANAGED"
	ListPropertiesParamsRentalModeMASTERLEASE ListPropertiesParamsRentalMode = "MASTER_LEASE"
)

// Valid indicates whether the value is a known member of the ListPropertiesParamsRentalMode enum.
func (e ListPropertiesParamsRentalMode) Valid() bool {
	switch e {
	case ListPropertiesParamsRentalModeMANAGED:
		return true
	case ListPropertiesParamsRentalModeMASTERLEASE:
		return true
	default:
		return false
	}
}

// ChangeStatusRequest 變更物件狀態的請求 body。
type ChangeStatusRequest struct {
	// Status 目標狀態，必須是四個合法值之一；是否允許從目前狀態轉換過去由狀態機另行判斷。
	Status ChangeStatusRequestStatus `json:"status"`
}

// ChangeStatusRequestStatus 目標狀態，必須是四個合法值之一；是否允許從目前狀態轉換過去由狀態機另行判斷。
type ChangeStatusRequestStatus string

// CreatePropertyRequest 建立物件的請求 body。金額欄位（area_ping、monthly_rent、management_fee）
// 一律是十進位數字的字串形式，不是 JSON number —— JSON number 無法在
// JavaScript 客戶端往返而不損失十進位精度。
type CreatePropertyRequest struct {
	// AreaPing 坪數，十進位數字字串，必須大於 0。
	AreaPing string `json:"area_ping"`

	// City 縣市，不可為空。
	City string `json:"city"`

	// DepositMonths 押金月數，不可為負數。
	DepositMonths int `json:"deposit_months"`

	// District 鄉鎮市區。
	District string `json:"district"`

	// Floor 樓層。
	Floor string `json:"floor"`

	// LandlordName 房東姓名。
	LandlordName string `json:"landlord_name"`

	// LandlordPhone 房東電話。
	LandlordPhone string `json:"landlord_phone"`

	// Layout 格局。
	Layout CreatePropertyRequestLayout `json:"layout"`

	// ManagementFee 管理費，十進位數字字串，未提供時預設為 0，不可為負數。
	ManagementFee *string `json:"management_fee,omitempty"`

	// MonthlyRent 月租金，十進位數字字串，必須大於 0。
	MonthlyRent string `json:"monthly_rent"`

	// RentalMode 經營模式——包租（MASTER_LEASE，業者向房東承租整個物件並轉租）或
	// 代管（MANAGED，業者只負責管理，租約只有一份）。
	RentalMode CreatePropertyRequestRentalMode `json:"rental_mode"`

	// RoomNo 房號。
	RoomNo string `json:"room_no"`

	// StreetAddress 街道地址，不可為空。
	StreetAddress string `json:"street_address"`
}

// CreatePropertyRequestLayout 格局。
type CreatePropertyRequestLayout string

// CreatePropertyRequestRentalMode 經營模式——包租（MASTER_LEASE，業者向房東承租整個物件並轉租）或
// 代管（MANAGED，業者只負責管理，租約只有一份）。
type CreatePropertyRequestRentalMode string

// ErrorBody 所有錯誤回應共用的統一形狀。
type ErrorBody struct {
	// Code 穩定、機器可讀的錯誤代碼。
	Code string `json:"code"`

	// Details 驗證失敗時，逐欄位的詳細原因（可省略）。
	Details *[]FieldError `json:"details,omitempty"`

	// Message 給人看的錯誤訊息。
	Message string `json:"message"`

	// RequestId 這個請求的 request id，方便對照 server 端日誌。
	RequestId string `json:"request_id"`
}

// FieldError 單一欄位的驗證失敗原因。
type FieldError struct {
	// Field 未通過驗證的欄位名稱。
	Field string `json:"field"`

	// Reason 該欄位未通過驗證的原因。
	Reason string `json:"reason"`
}

// HealthReport 一次健康檢查的彙整結果。
type HealthReport struct {
	// Checks 每個相依服務的健康狀態，key 為服務名稱（例如 postgres、redis）。
	Checks map[string]string `json:"checks"`

	// Status 整體健康狀態。
	Status HealthReportStatus `json:"status"`
}

// HealthReportStatus 整體健康狀態。
type HealthReportStatus string

// Property 包租代管服務的物件（房源）主檔。
type Property struct {
	// AreaPing 坪數，十進位數字字串，固定兩位小數。
	AreaPing      string    `json:"area_ping"`
	City          string    `json:"city"`
	CreatedAt     time.Time `json:"created_at"`
	DepositMonths int       `json:"deposit_months"`
	District      string    `json:"district"`
	Floor         string    `json:"floor"`

	// Id 物件 ID，由服務端產生。
	Id            openapi_types.UUID `json:"id"`
	LandlordName  string             `json:"landlord_name"`
	LandlordPhone string             `json:"landlord_phone"`
	Layout        PropertyLayout     `json:"layout"`

	// ManagementFee 管理費，十進位數字字串，固定兩位小數。
	ManagementFee string `json:"management_fee"`

	// MonthlyRent 月租金，十進位數字字串，固定兩位小數。
	MonthlyRent string             `json:"monthly_rent"`
	RentalMode  PropertyRentalMode `json:"rental_mode"`
	RoomNo      string             `json:"room_no"`

	// Status 新建物件一律為 VACANT。
	Status        PropertyStatus `json:"status"`
	StreetAddress string         `json:"street_address"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

// PropertyLayout defines model for Property.Layout.
type PropertyLayout string

// PropertyRentalMode defines model for Property.RentalMode.
type PropertyRentalMode string

// PropertyStatus 新建物件一律為 VACANT。
type PropertyStatus string

// PropertyList 分頁列出物件的回應。
type PropertyList struct {
	// Items 當頁資料；查無資料時為空陣列（不是 null）。
	Items []Property `json:"items"`

	// Total 套用篩選後、分頁前的總筆數，與 items 長度無關。
	Total int `json:"total"`
}

// UpdatePropertyRequest 更新物件欄位的請求 body。所有欄位皆為選填——未出現的欄位視為
// 「不更動」。刻意沒有 status 欄位：變更狀態一律走
// POST /api/v1/properties/{id}/status，不能透過這個 endpoint 繞過狀態機。
// 金額欄位（monthly_rent、management_fee）與 CreatePropertyRequest 一樣，
// 一律是十進位數字的字串形式，不是 JSON number。
type UpdatePropertyRequest struct {
	// DepositMonths 押金月數，若提供不可為負數。
	DepositMonths *int `json:"deposit_months,omitempty"`

	// LandlordName 房東姓名。
	LandlordName *string `json:"landlord_name,omitempty"`

	// LandlordPhone 房東電話。
	LandlordPhone *string `json:"landlord_phone,omitempty"`

	// Layout 格局，若提供必須是四個合法值之一。
	Layout *UpdatePropertyRequestLayout `json:"layout,omitempty"`

	// ManagementFee 管理費，十進位數字字串，若提供不可為負數。
	ManagementFee *string `json:"management_fee,omitempty"`

	// MonthlyRent 月租金，十進位數字字串，若提供必須大於 0。
	MonthlyRent *string `json:"monthly_rent,omitempty"`
}

// UpdatePropertyRequestLayout 格局，若提供必須是四個合法值之一。
type UpdatePropertyRequestLayout string

// ListPropertiesParams defines parameters for ListProperties.
type ListPropertiesParams struct {
	// Page 頁碼（1-based）。未提供或非正整數時預設為 1。
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize 每頁筆數。未提供或非正整數時預設為 20，上限 100。
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Status 依物件狀態篩選；未提供時不篩選。
	Status *ListPropertiesParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// RentalMode 依經營模式（包租／代管）篩選；未提供時不篩選。
	RentalMode *ListPropertiesParamsRentalMode `form:"rental_mode,omitempty" json:"rental_mode,omitempty"`

	// City 依縣市篩選；未提供時不篩選。
	City *string `form:"city,omitempty" json:"city,omitempty"`
}

// ListPropertiesParamsStatus defines parameters for ListProperties.
type ListPropertiesParamsStatus string

// ListPropertiesParamsRentalMode defines parameters for ListProperties.
type ListPropertiesParamsRentalMode string

// CreatePropertyJSONRequestBody defines body for CreateProperty for application/json ContentType.
type CreatePropertyJSONRequestBody = CreatePropertyRequest

// UpdatePropertyJSONRequestBody defines body for UpdateProperty for application/json ContentType.
type UpdatePropertyJSONRequestBody = UpdatePropertyRequest

// ChangePropertyStatusJSONRequestBody defines body for ChangePropertyStatus for application/json ContentType.
type ChangePropertyStatusJSONRequestBody = ChangeStatusRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListProperties 分頁列出物件
	// (GET /api/v1/properties)
	ListProperties(w http.ResponseWriter, r *http.Request, params ListPropertiesParams)
	// CreateProperty 建立一筆包租代管物件
	// (POST /api/v1/properties)
	CreateProperty(w http.ResponseWriter, r *http.Request)
	// GetProperty 以 id 查詢單一物件
	// (GET /api/v1/properties/{id})
	GetProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// UpdateProperty 更新物件欄位
	// (PATCH /api/v1/properties/{id})
	UpdateProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// ChangePropertyStatus 變更物件狀態
	// (POST /api/v1/properties/{id}/status)
	ChangePropertyStatus(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetHealthz 健康檢查
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ListProperties 分頁列出物件
// (GET /api/v1/properties)
func (_ Unimplemented) ListProperties(w http.ResponseWriter, r *http.Request, params ListPropertiesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateProperty 建立一筆包租代管物件
// (POST /api/v1/properties)
func (_ Unimplemented) CreateProperty(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetProperty 以 id 查詢單一物件
// (GET /api/v1/properties/{id})
func (_ Unimplemented) GetProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateProperty 更新物件欄位
// (PATCH /api/v1/properties/{id})
func (_ Unimplemented) UpdateProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ChangePropertyStatus 變更物件狀態
// (POST /api/v1/properties/{id}/status)
func (_ Unimplemented) ChangePropertyStatus(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetHealthz 健康檢查
// (GET /healthz)
func (_ Unimplemented) GetHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListProperties operation middleware
func (siw *ServerInterfaceWrapper) ListProperties(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPropertiesParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "rental_mode" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "rental_mode", r.URL.Query(), &params.RentalMode, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "rental_mode"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "rental_mode", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "city" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "city", r.URL.Query(), &params.City, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "city"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "city", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProperties(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProperty operation middleware
func (siw *ServerInterfaceWrapper) CreateProperty(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProperty(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProperty operation middleware
func (siw *ServerInterfaceWrapper) GetProperty(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProperty(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProperty operation middleware
func (siw *ServerInterfaceWrapper) UpdateProperty(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProperty(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ChangePropertyStatus operation middleware
func (siw *ServerInterfaceWrapper) ChangePropertyStatus(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChangePropertyStatus(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealthz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/properties", wrapper.ListProperties)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/properties", wrapper.CreateProperty)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/properties/{id}", wrapper.GetProperty)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/properties/{id}", wrapper.UpdateProperty)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/properties/{id}/status", wrapper.ChangePropertyStatus)
	})

	return r
}

type ListPropertiesRequestObject struct {
	Params ListPropertiesParams
}

type ListPropertiesResponseObject interface {
	VisitListPropertiesResponse(w http.ResponseWriter) error
}

type ListProperties200JSONResponse PropertyList

func (response ListProperties200JSONResponse) VisitListPropertiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListProperties400JSONResponse ErrorBody

func (response ListProperties400JSONResponse) VisitListPropertiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePropertyRequestObject struct {
	Body *CreatePropertyJSONRequestBody
}

type CreatePropertyResponseObject interface {
	VisitCreatePropertyResponse(w http.ResponseWriter) error
}

type CreateProperty201JSONResponse Property

func (response CreateProperty201JSONResponse) VisitCreatePropertyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProperty400JSONResponse ErrorBody

func (response CreateProperty400JSONResponse) VisitCreatePropertyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProperty409JSONResponse ErrorBody

func (response CreateProperty409JSONResponse) VisitCreatePropertyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetPropertyRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetPropertyResponseObject interface {
	VisitGetPropertyResponse(w http.ResponseWriter) error
}

type GetProperty200JSONResponse Property

func (response GetProperty200JSONResponse) VisitGetPropertyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetProperty400JSONResponse ErrorBody

func (response GetProperty400JSONResponse) VisitGetPropertyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetProperty404JSONResponse ErrorBody

func (response GetProperty404JSONResponse) VisitGetPropertyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePropertyRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdatePropertyJSONRequestBody
}

type UpdatePropertyResponseObject interface {
	VisitUpdatePropertyResponse(w http.ResponseWriter) error
}

type UpdateProperty200JSONResponse Property

func (response UpdateProperty200JSONResponse) VisitUpdatePropertyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateProperty400JSONResponse ErrorBody

func (response UpdateProperty400JSONResponse) VisitUpdatePropertyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateProperty404JSONResponse ErrorBody

func (response UpdateProperty404JSONResponse) VisitUpdatePropertyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ChangePropertyStatusRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *ChangePropertyStatusJSONRequestBody
}

type ChangePropertyStatusResponseObject interface {
	VisitChangePropertyStatusResponse(w http.ResponseWriter) error
}

type ChangePropertyStatus200JSONResponse Property

func (response ChangePropertyStatus200JSONResponse) VisitChangePropertyStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ChangePropertyStatus400JSONResponse ErrorBody

func (response ChangePropertyStatus400JSONResponse) VisitChangePropertyStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ChangePropertyStatus404JSONResponse ErrorBody

func (response ChangePropertyStatus404JSONResponse) VisitChangePropertyStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ChangePropertyStatus409JSONResponse ErrorBody

func (response ChangePropertyStatus409JSONResponse) VisitChangePropertyStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse HealthReport

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthz503JSONResponse HealthReport

func (response GetHealthz503JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListProperties 分頁列出物件
	// (GET /api/v1/properties)
	ListProperties(ctx context.Context, request ListPropertiesRequestObject) (ListPropertiesResponseObject, error)
	// CreateProperty 建立一筆包租代管物件
	// (POST /api/v1/properties)
	CreateProperty(ctx context.Context, request CreatePropertyRequestObject) (CreatePropertyResponseObject, error)
	// GetProperty 以 id 查詢單一物件
	// (GET /api/v1/properties/{id})
	GetProperty(ctx context.Context, request GetPropertyRequestObject) (GetPropertyResponseObject, error)
	// UpdateProperty 更新物件欄位
	// (PATCH /api/v1/properties/{id})
	UpdateProperty(ctx context.Context, request UpdatePropertyRequestObject) (UpdatePropertyResponseObject, error)
	// ChangePropertyStatus 變更物件狀態
	// (POST /api/v1/properties/{id}/status)
	ChangePropertyStatus(ctx context.Context, request ChangePropertyStatusRequestObject) (ChangePropertyStatusResponseObject, error)
	// GetHealthz 健康檢查
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListProperties operation middleware
func (sh *strictHandler) ListProperties(w http.ResponseWriter, r *http.Request, params ListPropertiesParams) {
	var request ListPropertiesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListProperties(ctx, request.(ListPropertiesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProperties")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPropertiesResponseObject); ok {
		if err := validResponse.VisitListPropertiesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateProperty operation middleware
func (sh *strictHandler) CreateProperty(w http.ResponseWriter, r *http.Request) {
	var request CreatePropertyRequestObject

	var body CreatePropertyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateProperty(ctx, request.(CreatePropertyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateProperty")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePropertyResponseObject); ok {
		if err := validResponse.VisitCreatePropertyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProperty operation middleware
func (sh *strictHandler) GetProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetPropertyRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProperty(ctx, request.(GetPropertyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProperty")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPropertyResponseObject); ok {
		if err := validResponse.VisitGetPropertyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateProperty operation middleware
func (sh *strictHandler) UpdateProperty(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdatePropertyRequestObject

	request.Id = id

	var body UpdatePropertyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateProperty(ctx, request.(UpdatePropertyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateProperty")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdatePropertyResponseObject); ok {
		if err := validResponse.VisitUpdatePropertyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ChangePropertyStatus operation middleware
func (sh *strictHandler) ChangePropertyStatus(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request ChangePropertyStatusRequestObject

	request.Id = id

	var body ChangePropertyStatusJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ChangePropertyStatus(ctx, request.(ChangePropertyStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ChangePropertyStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ChangePropertyStatusResponseObject); ok {
		if err := validResponse.VisitChangePropertyStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(w http.ResponseWriter, r *http.Request) {
	var request GetHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FvrU9tYlv9XVNr5sFvrAUN3dmb8ZYsNdEIXAxSP3tpqsi4FK+BpkN2y6B0mRZVsIMjYxk4CJn6EV3gT",
	"zDPBMYL8L23fK+mT/4Wte68ly7ZMnOekq/oTWJbuPefc8/idn44f0sOeca+HYznBRzse0r7hUXacwf/e",
	"HmW4EbZfYIQJXx/78wTrE9BlF+sb5t1ewe3haAetZuZh6lwJ7hUuXyshEc6GlOSMehCCJwHqvsc1mRcD",
	"tI328h4vywtuluyBl6xdS0ll4G6CrFKUw+DtrLYmwWdHIJUCYgjEJHi2BES58CZUyIpFOYW+im2DWb+6",
	"ewKuV5RUBgQj5HH1KgijKc2/ABYulcUTchHurYLotroeBtImjF8Q0VhuYpx2/Ej/0Ha7rXuAttE9t28P",
	"9nZ2tNM2uq+ju+eHtoHO7ju0jW7v6OrsH+hop+/ZaGHSy9IO2ifwbm6Enpqy0Tz784SbZ11oqZJ+5fs8",
	"9//GDgv0lI2+zbOMwPYSc0zWtSq4zCkHoZJVq+2pzT3W1iPw5UzhKlKUJYZnGafXzY3kRf+4hxNGxyad",
	"PMsJ6CPDMSPsOMsJzgcsW5SDQ1whK4LrELJcxK+Jp4WrCFzKgsNlJTkDDpcL2VNwtQHkaFEOF7IR+OyI",
	"+r6/p5viJsbvszz1q7j4q7hYcUmZWUenkt4d4r5nfmH6sRIUyGxA6bVycASuRfXtoiri1WIRsHli7Kuc",
	"XoPcdl4MDHE1HmLoZGGa5/twKYvco1IBIr3hNmBzB8Zlyl7yP0YQWB49/r9DQ65//9ehoSb099/+8w90",
	"zWHa6GG3MGnhndkXIBsghgHRIyWQU/ZyZPmaFVys1+NzC058HhaeDudlbe4xTEtEFWNF9XQNLmUrFnVz",
	"AjvC8nhVN9ph2MJftJmgtpAB2QCIiHVEejDm8fAWkuw+BSebdZ4ZYzjXmId3OTlmnLV4VnoLn5+Anacg",
	"FnnXCt5RD1d3CS11qe6d1F1i0jNhoTNck8GJWBnE/323p6vDOdjdiQK5s7u9o7eju72je8DZP9g50EHb",
	"6P67bX0d7eWPnd13ujqcfT09f7UIaxtdGUAWPpFZV2KP1NPLG/wRpvdhNFa4TsFEQFuLqbuHSiBH2esd",
	"+/u5qjngLUyUlpSdVW3u8WcNF7Q3M+Yc97isLPT6qTK3CnfXgRwl6QOEZ5Wd1aIs/bWtf6Cjz9nV0dbf",
	"gey0daiKsyD2mPgEDL5Vdlbh0jkQS4mwkN1Wr4L42SCU4kNc4fKFklnHK3W33eloLy8S3VdP19TTl+R8",
	"inJY2VlVzmdAdB+mg4WsWLi8KspBPffo3mMWiLbRpVUtHYP3eMadnMfSodXEah1X9gk8ywpOxuXiWZ9F",
	"WlDXlzX/U5A+Bs/FRhJNVd3BecuUJmo21LNAWX4jvGymnFvlVjXprPLIq9NETdBb1cEOnvfw/+VxWeRZ",
	"GBRhOqiFj9T9TZBagXNBMHuiLO4qyRnl1QmqX1cbSki0AhbD1i64twcyybzoR/U/sQuiR2pGVJIzZAvk",
	"RBty3TwuMO4xi5PS9pbVwyDYPIFLyzCBqoImxkhJRvV670w5PwYLqyC1VpQldIhpv7K0RXyOttFugR3H",
	"q/6BZx/QDvpfmssorLkEwZq/c7NjLmwoJEpJNobnmUkc+azPx4xYqftqu5DLKemQoaK6Ow/9R3VU5AkG",
	"cbpdFlqKCSCGCPpQkjNU6V7K7UKhFn9TuH4LjiPK7A7lY/lfEBo4OILLW+p+uCF3Jd6jK1IhipXPmOxR",
	"iwrimUJWNA7AfDzkGKzc5QFa0Cpr7mtiUvMvkFWU5AxZF8Qiyu5JXTMyPvR0TUjvnZKna1c1C3azpYig",
	"xiZWxrnLMmPCaB/r9fAWhQDbZh34t0DuAu5vwNUttP9VAi6dK69icCVtGU2j7PBPBI65XG60EjPWW3GH",
	"RbxUGPIoipJ3Klu4fg7TERBKoF2xEAbI/4mdpJRAjnxNLFyUpcJ1CGwHKK/HJ4zwrC8v+nnW5fYZ8VOj",
	"fr2WAi6daweL5j0rAYPnJ5zeRnjGxboaRvY23TZWJ6GDewsnxZWPVC3DHqS2FWUJlb1crCgHC9lLuL9o",
	"dSIfBYtTOZBJgtk95MnH0Xp4g5T6h61TNyLj2i9wX+NyMtj5Hnj4cfQf7WIE9o+CG1eFBkDyzZC3PqSt",
	"+cYqmRFDU50IJiiLJ6UDODhSFjeUxVLFNgSfmHC7GkLEDSDeGxDt14xbP4nDfAJ8+inEqIKoHwf4LGBd",
	"neQTP0aNfAm8or4bIX9CNHw68sEKVtbcMuF1vWd8VmU+HA6fDWBW+es7EaeRh98BPSsSU4UVbsrcXW5L",
	"TkZ6pK35gbQM5nIGM0MAqlWuNiBeVeQtvdbW/OrZHIwninIKVeKZdfIRJgIE62uJF0BaRmWQUDDcxNjY",
	"+0FHowZZAEfBIzBjFuptLSOQfbSn+bPgOpwX/SWFgwhQKdkr5fARqTCqNEdhKSht6QLktpWZdW05bU1a",
	"VHsRFl6XweoMBvERvZMgg6lzGD8mx1CG3RU0Gekj9C8fKYEc0mz9gHShML2PzjF6bcA7dTuuBHJDXJ6Q",
	"ValzEFrKi5G8GADSJZyJwtMnMB2kiOtROv2WLBGgGFuQIFdfHQ9xvT39A1Qz43U3/9LSXPaM5odu11Qz",
	"WYN0eOr0lSZGES7EYJtiOZfX4+YESnmzovkXDOYSN6tV1N+76D50UpaMI4UA4e6Lohz+OEbQmr17T/ZL",
	"DW0RgqRBGuw3wEqZtbqZxv76+aubj+dL01VVZv1w3mqqJvmgS27ugadB4A6OI2AzTt0dGOil2no7S37i",
	"FsbQmsOjE8OjE61U7ZPoXtpG/8LyPrK4vamlyY6M4/GyHON10w76G3wJ60PipzaRoKsjrFWZwnipcLlF",
	"lUsfhfBu/BhIx6o0DxeegFy0KEsgFoaJgBZ/im52u3Ab9nJd3faTO7TIq6Ic1vxvwWyElAL14kxNrOrE",
	"Gc7hFPLr96kcILUCAmdKcsaihBTl1BBXtVpVgSzKYfKcuVJSP94rymEiD+ZW9bSEjMUgu3S6aAeNyrqp",
	"f0Xm5ZlxVmB5H+34sYb7WPMrG3JRllr+eJ/xsS6idpnMleLa8xV4+AIuncOlbAW321Kq1GiZnydYHmEm",
	"kqtoL2E6SJ0mh/eAmRgTaEeLjR53c+5xlAharArpw9ruGsmIbduoZK2Edp7XEjGqxW6/WU6nz/2POsK2",
	"2lFu+XtJWrv9fWUvXD+veGWITxvBIRNXXshGyPX6UhowsCzip3mdZyWvichGwVNisaM6CR38UCWqkG2N",
	"Jg03KdZi47dWHypbCfCXhare8h7Cdz6vh/ORlNRqtxMilhNKKZ7xesfcwzgKm/9WosjK6zUCYjEcx9m5",
	"KgBWt9S9DSjFwDxu36ds9LcNbc/+nRn3jrFlxpj+oa2rs71toLOn2/ldW2cX9haD+/3RYAr18NXJPtqo",
	"7Ua40cgkBjdbwRNXMpwO2t7yfVNTE27gGrJHmTOvawwQnUYhX0k1YtugXSbGxxl+0rKVQaWLGUHKmrHc",
	"vSkb7fVY4m9Ta4uSeQkVV3e5KF27KEu2ZYhTUlkQC1PIx/KiX28q86K/sqnMi37cVOZFf6mppAzajGB2",
	"bS6ibs6ByxzcX8Qv3KbVjQMYeqK8WrKuBJWYuHwu+guJxv3HxMjRf266ZdebZAetzuVAeBlkA7XdrKPV",
	"TGzRYHMHZIIgIhrts4O+VdPbOmhlIYTgzrOF2j7XQdv/0tL6zbe3/uNPfy633A5LCFmNCemWVru9yW6v",
	"7soddOstu91OlKogUKpTksGN0G21lICDBtd7qiSByLJ6cYT6jswrVHsoNbHauO9bz01MVfaXAj/BTtUk",
	"pJZPnpCs4o943xdNRlUcSlVS0pHxPyshkWYczO6AzBurhITs85cPsk9vX09vR9/A/zjbB3u7Om+3Ea82",
	"NCRpRYuLSjBsJApwcQoOn4H07mfV+eati7JUmamsMjMe/ClkReXwkbl3uDlLT9noOlSDqU2oTIF3WMGU",
	"/25EwgZxbsIJqDMpwwS3i66OQ7M938GqfxEQ8ZUACLfLEj4QUgAV0sHBzvZ/Vsi6XRSheCrFMUzz7ceF",
	"a3fPgPO7nsHu9opwhcHrQjYCpGMYngOZpBE2nxstKTPrVTvWRmOpMS5hK/yK+Z1wiRGGRy268ogIVleh",
	"uGMmLpXkjPZ8pcTw6ZweYUDyot/gZvKi38yYoY+l0Sc/IarUszl1d17vy/WX9Pc9rkmqkD2sx3RW8ZxF",
	"OUV4TnRxYQtElyupTkKbDnGWfCf1/nQn1ds2cPvuEFdLcxYuLwtXSyQskczYYtr0FUxPA+kCxo+pMo9v",
	"je8qSeSvI799IMCshmR/shOw1nAcWBPqDSGnL5SF8fmS48bv+1ZA4IxcBNeojIJMGC6dm2L0d2hVF1qh",
	"9keKU79n8qpMXvu+6P2xVHP5Pa91U2ymtEppMjkDFlHTA2a3QPRFUQ4rr5+a59GLsqRuh6jSTpNNtxlu",
	"gGc4Hx63KcpBMqwzxJFzhOJOXgwYZ0qG3ItykjTbvz5a1MmuvOg3rpVZr7zoH+KM6zoBlhf95Vt+ffRE",
	"v44KwuxrbfMZpooPQCxsHq1H2RwP6ZRXfKL3/EFSF7TnK/AMdeClYXz8ESYCIBMGs7vIP9PT4OgAzG4R",
	"ehfkDuq06/iHCHoO6ddJv99uUtcdycxINt4KW/ws4ytK5+Swv650bvDEtcjbGMfwm2KnfCwUyqZ6RFDk",
	"ld1XmfYlg4Erp30gLatSEIhyUf69MFT620cyD53d2PWc/QNtA4P9zoG+tu7+TuSHFXojpfGPk+D8vLk2",
	"gOuVsk+ReAHSMWV6U/E5KYryj6QM+QwZyuYy/RSrtprW/ujrpmo6ikdT/3HDG8sVsFZiiGH6pZo7UKU5",
	"MPvaPDhalKXe8jBoX2kYlChT+hkYnvHEBQTM7mrTu+bHtemr0vBrIgBSK1SrHb8Iu7xEHZ3pPmQR8323",
	"7N9Yl6Q7rHC3pNYH5Vmzbxljtvq4K+0gc6l45pV8ME2Z6R8b8oWKsWCrKMFqq9IcmZapnNV9ZNgUbXjL",
	"/s0nUMzl+T+uvmrGJO4nU1CdOwPHjxEgqZxENk7agoMzjUmb/Jq4MfJpdDeed7cEHqksOI6oF0fg+jFp",
	"eZXXfhRUwTcgk6RGPT5Bn0DCI89H21oypaReqP4rlI3R9w6kDKUsniAvvjpVnhyDjekhrihLMP0S7q1q",
	"8ZCSkFH7n32p7m2jfw5fADlKbkSo8SQHMkmENrEw+nT+YF8XpWaeFi631IsjZfEEHi2C4wgeegKrOWVz",
	"AVXniy0we4FHPZa1RAzGZTJQoMuGCiJYXSO/ccGBMcGP0Q66mZ66N/X/AQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
